server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml 

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "go-services"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "go-services"
          __path__: "/app/logs/*.log" 

    pipeline_stages:
      - regex:
          expression: "^(?P<level>INFO|WARN|ERROR|DEBUG) (?P<message>.*)$"
      - labels:
          level: level
